### ISSUE TITLE
Unable to start Inference_demo : ModuleNotFoundError: No module named 'rich' 

### ISSUE THREAD

**Issue by shackdown** [huggingface/huggingface-inference-toolkit#93]
Hi, i try to follow the blog [https://huggingface.co/blog/s2s_endpoint](https://huggingface.co/blog/s2s_endpoint)

First i added the HF_MODEL_ID = andito/s2s in env variable, it seems to be mandatory even if we set MODEL in creation form.

<img width="1269" alt="image" src="https://github.com/user-attachments/assets/60f6eef1-322e-4cc4-93d1-dc49edaaaf80">

And after i obtained the issue below

```

[Server message]Endpoint failed to start
See details
Exit code: 3. Reason: 00:00, 49.37it/s]
Fetching 77 files: 100%|██████████| 77/77 [00:02<00:00, 37.88it/s]
2024-10-23 09:17:16 - huggingface_inference_toolkit - INFO - Initializing model from directory:/opt/huggingface/model
2024-10-23 09:17:16 - huggingface_inference_toolkit - INFO - Found custom pipeline at /opt/huggingface/model/handler.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 569, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 670, in startup
    await handler()
  File "/app/webservice_starlette.py", line 62, in prepare_model_artifacts
    inference_handler = get_inference_handler_either_custom_or_default_handler(
  File "/app/huggingface_inference_toolkit/handler.py", line 90, in get_inference_handler_either_custom_or_default_handler
    custom_pipeline = check_and_register_custom_pipeline_from_directory(model_dir)
  File "/app/huggingface_inference_toolkit/utils.py", line 170, in check_and_register_custom_pipeline_from_directory
    spec.loader.exec_module(handler)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/huggingface/model/handler.py", line 5, in <module>
    from s2s_pipeline import main, prepare_all_args, get_default_arguments, setup_logger, initialize_queues_and_events, build_pipeline
  File "/opt/huggingface/model/s2s_pipeline.py", line 10, in <module>
    from VAD.vad_handler import VADHandler
  File "/opt/huggingface/model/VAD/vad_handler.py", line 3, in <module>
    from baseHandler import BaseHandler
  File "/opt/huggingface/model/baseHandler.py", line 3, in <module>
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'

Application startup failed. Exiting.

```

thanks for your help
;)

**Comment by alvarobartt** [comment]
Hi here @shackdown I believe that's because as mentioned in the blog, the installation of the extra requirements is moved into a custom Dockerfile, meaning that it's not pulling the default PyTorch Inference container, meaning that extra dependencies required by that model as e.g. `rich` in this case, are not available within the container.

The following dependencies should be downloaded on start up https://huggingface.co/andito/s2s/blob/main/requirements.txt, not sure if `rich` is a dependency of any of those, I'll try to reproduce on my end.

cc @andimarafioti as he's one of the authors of the post you linked above and may be able to assist better 🤗

**Comment by shackdown** [comment]
Thanks @alvarobartt , i restarted from scratch and now i have another issue 

```
Exit code: 1. Reason: ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 412, in main
    run(
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/importer.py", line 22, in import_from_string
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/webservice_starlette.py", line 16, in <module>
    from s2s_handler import EndpointHandler
ModuleNotFoundError: No module named 's2s_handler'
```

I will continue to understand why, but if somebody has the solution :)

thanks

**Comment by alvarobartt** [comment]
Hi here again @shackdown!

I believe that the recommended way of deploying that is using a custom Docker container previously pushed to the Docker Hub (or to any other public Docker Registry) that contains the code, since the default container used for inference on Inference Endpoints is just assuming that the handler code lives under the `handler.py` file, whilst the requirements are installed from the `requirements.txt` file. In this case, since it contains more custom code other than the actual `handler.py`, you may need to build the Dockerfile with the instructions at https://huggingface.co/blog/s2s_endpoint, and then push it to a Docker Registry; so that finally you can deploy the endpoint on Inference Endpoint using a custom container, being the S2S one.

Hope that helps, otherwise let me know if you find any issue! 🤗

**Comment by shackdown** [comment]
Hi @alvarobartt , thanks for your help. I can run now on my Mac. 

Have a wonderful day !
